# services:
#   - type: web
#     name: expense-tracker
#     env: python
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "./start.sh"
#     plan: free
services:
  - type: web
    name: expense-tracker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
